### ISSUE TITLE
FOLLOW_VIDEO modes missing

### ISSUE THREAD

**Issue by luc-ass** [aegjoyce/custom-ambilight#3]
Hey there, first of all a big thanks for all the hard work you put into this!

I am not able to control any video modes on my TV using custom ambilight. The only modes exposed are the following:
![Bildschirmfoto 2024-10-20 um 18 06 14](https://github.com/user-attachments/assets/2498add9-4afd-447a-b457-aa030acda2a6)

TV model: 43PUS7805/12

Through the developer tools the following is exposed:
```yaml
effect_list:
  - "FOLLOW_AUDIO: ENERGY_ADAPTIVE_BRIGHTNESS: Expert"
  - "FOLLOW_AUDIO: ENERGY_ADAPTIVE_COLORS: Expert"
  - "FOLLOW_AUDIO: KNIGHT_RIDER_ALTERNATING: Expert"
  - "FOLLOW_AUDIO: KNIGHT_RIDER_CLOCKWISE: Expert"
  - "FOLLOW_AUDIO: PARTY: Expert"
  - "FOLLOW_AUDIO: RANDOM_PIXEL_FLASH: Expert"
  - "FOLLOW_AUDIO: SPECTRUM_ANALYZER: Expert"
  - "FOLLOW_AUDIO: STROBE: Expert"
  - "FOLLOW_AUDIO: VU_METER: Expert"
  - "FOLLOW_COLOR: AUTOMATIC_HUE: Expert"
  - "FOLLOW_COLOR: MANUAL_HUE: Expert"
  - "Mode: expert"
  - "Mode: internal"
  - "Mode: manual"
supported_color_modes:
  - hs
  - onoff
effect: "FOLLOW_VIDEO: GAME"
color_mode: onoff
brightness: null
hs_color: null
rgb_color: null
xy_color: null
friendly_name: Wohnzimmer-TV Ambilight
supported_features: 4
```

I was able to capture the commands my phone sends to the TV with Wireshark. The following codes are transmitted and work just finde:
Standard:
`{"values":[{"value":{"Nodeid":120,"Controllable":true,"Available":true,"data":{"selected_item":121}}}]}`
Natural: 
`{"values":[{"value":{"Nodeid":120,"Controllable":true,"Available":true,"data":{"selected_item":122}}}]}`
Sport:
`{"values":[{"value":{"Nodeid":120,"Controllable":true,"Available":true,"data":{"selected_item":123}}}]}`
Vivid:
`{"values":[{"value":{"Nodeid":120,"Controllable":true,"Available":true,"data":{"selected_item":124}}}]}`
Game:
`{"values":[{"value":{"Nodeid":120,"Controllable":true,"Available":true,"data":{"selected_item":125}}}]}`

To me all this looks like my TV doesn't expose the video setting sin the way the plugin expects it. Would it be possible to add the commands above to the plugin?

Thank you very much
Lucas
